#common
server:
    port: 80
    context-path: '/'
    compression:
        enabled: false
    display-name: 'Skeleton for SpringBoot2'
    error:
        include-stacktrace: never
        whitelabel:
            enabled: true
    tomcat:
        accesslog:
            enabled: false
            pattern: common
            prefix: access_log
            suffix: .log
        max-threads: 0
        uri-encoding: UTF-8
        protocol-header: x-forwarded-proto
    session:
        timeout: 600
        cookie:
            domain: .ahnstar.com
            path: '/'

spring:
    banner:
        charset: UTF-8
        location: 'classpath:config/banner.txt'
    profile:
        active: local
    jpa:
        hibernate:
            ddl-auto: none
        generate-ddl: false
        show-sql: true
    datasource:
        driver-class-name: 'net.sf.log4jdbc.sql.jdbcapi.DriverSpy'
        url: 'jdbc:log4jdbc:mysql://localhost:3306/db_skeleton?characterEncoding=UTF-8&serverTimezone=UTC'
        username: ahnstar83
        password: faith
    http:
        multipart:
            max-file-size: 5MB
            max-request-size: 100MB
        
logging:
    level:
        root: info
        org:
            springframework:
                core: error
                beans: error
                context: error
                web: error
        jdbc:
            sqlonly: error
            audit: error
            resultset: error
            resultsettable: error
            connection: error
            sqltiming: error
        com:
            ahnstar: error
    pattern:
        console: '[%d{yyyy-MM-dd HH:mm:ss.SSS}] %level: %c - %msg%n'
        
